# Generated by Django 5.1 on 2024-08-24 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vista_principal', '0002_remove_cliente_direccion_cliente_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(blank=True, default=0, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('orden', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='vista_principal.orden')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vista_principal.producto')),
            ],
        ),
        migrations.DeleteModel(
            name='orden_items',
        ),
    ]
